
name: Deploy Spring Boot To EC2 (SSH)
on:
  push:
    branches: ["main"]

jobs:
  admin1:
    runs-on: ubuntu-latest

    steps:
    - name: Checout
      uses: actions/checkout@v4
      
    - name: Set Up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "17"

    - name: Build (Maven)
      run: mvn -B -DskipTests package

      
    - name: Copy jar to EC2(/opt/htuweb)
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_P_KEY }}
        source: "target/*.jar"
        target: "/opt/htuweb"
      
    - name: Active jar as app.jar + restart service
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_P_KEY }}
        script: |
          set -euo pipefail 
          cd /opt/htuweb
          
          ls -lah /opt/htuweb/target || true
          
          JAR="$(ls -t /opt/htuweb/target/*jar | head -n 1)"
          echo "Using $JAR"
          mv "$JAR" /opt/htuweb/app.jar
          sudo systemctl daemon-reload
          sudo systemctl restart htuweb
        
